### ISSUE TITLE
docker启动的程序如何配置http-proxy？

### ISSUE THREAD

**Issue by PanYu333** [yakami129/VirtualWife#23]
dokcer启动再服务器上的virtual wife，添加了openai key，但仍然不能对话，该如何正确配置http-proxy？

**Comment by yakami129** [comment]
高级设置可以开启http-proxy

**Comment by tomridder** [comment]
关于使用Docker启动后，无法访问OpenAI问题，如何解决
第一步请排查：你的梯子是否正常
第二步请排查：在高级设置中，将http-proxy设置开启，设置地址[http://host.docker.internal:23457，注意这里的端口号请配置你代理的端口号]
===================

请问下 这里的端口号 是计算机上 docker程序 所对应的端口号吗
