### ISSUE TITLE
baichuan-inc/Baichuan2-7B-Chat-4bits 模型兼容性问题

### ISSUE THREAD

**Issue by dgeeeeeed** [yakami129/VirtualWife#43]
目前的问题是调用 chatStream 接口是，过长的输入不能被正确返回，会返回空字符。

**Comment by dgeeeeeed** [comment]
已知问题：re正则表达式的问题
增加 re.DOTALL 能够解决这个模型输出格式不匹配的问题
if re.match(r"^(.+[。．！？~\n]|.{10,}[、,])", realtime_callback.message_buffer, re.DOTALL):
问题2：chatStream 接口是，过长的输入不能被正确返回
已知在一些参数没有被正确设置时，会出现这个问题。但是在build_body中的参数调节似乎没有被这个接口响应？chat接口反而能正常工作

**Comment by yakami129** [comment]
v2.0.6 已经修复该问题
