### ISSUE TITLE
能够对接上ChatGPT模型，并且日志也有反馈如下图，但是就应用上就是没得声音说出来，本地编译运行。

### ISSUE THREAD

**Issue by chenzhizhuan** [yakami129/VirtualWife#63]
![image](https://github.com/yakami129/VirtualWife/assets/4384043/a6fb88e6-d287-482b-8559-612601785192)
![image](https://github.com/yakami129/VirtualWife/assets/4384043/ea04c849-f2cc-4348-904e-39b84225b630)
![image](https://github.com/yakami129/VirtualWife/assets/4384043/c4ac7b09-a643-456a-b0b8-b182d1ef2eca)

**Comment by yakami129** [comment]
是不是websocket 没有正常连接，请继续排查一下，并给出详细日志

**Comment by chenzhizhuan** [comment]
ws前端显示是正常的，如下图：
![image](https://github.com/yakami129/VirtualWife/assets/4384043/67eafd79-30d4-4247-ac8a-bbc34272bb61)
ws本地开发模式，请求连接如下图：
![image](https://github.com/yakami129/VirtualWife/assets/4384043/b20730dd-822f-4e50-aa51-a7614891f09d)
大模型openai后台，日志如下图：
![image](https://github.com/yakami129/VirtualWife/assets/4384043/2063acc2-7755-41ea-aed8-79c948256b68)
![image](https://github.com/yakami129/VirtualWife/assets/4384043/855010a4-ba75-444a-9c45-8405fdf59487)

**Comment by chenzhizhuan** [comment]
本地开发websocket和正式环境的路径不一样，现在修复，已解决。感谢大佬。
