### ISSUE TITLE
linux部署，问问题有问题

### ISSUE THREAD

**Issue by wangbinxu** [yakami129/VirtualWife#69]
![image](https://github.com/yakami129/VirtualWife/assets/55842172/4afbfaaa-3639-4e0b-8bc9-ad4c11c88820)
![image](https://github.com/yakami129/VirtualWife/assets/55842172/9473ff25-4f30-4baa-a1f4-54723cddf837)

**Comment by yakami129** [comment]
方便把sys_config.json 发我一下吗，f12 看下或者配置的接口可以获取

**Comment by tomridder** [comment]
有人物出现，配置了 key和 baseurl，但是一直不回复，是不是http-proxy导致的
=================
关于使用Docker启动后，无法访问OpenAI问题，如何解决 第一步请排查：你的梯子是否正常 第二步请排查：在高级设置中，将http-proxy设置开启，设置地址[http://host.docker.internal:23457，注意这里的端口号请配置你代理的端口号]
================
请问下 这里的端口号 是计算机上 docker程序 所对应的端口号吗

**Comment by yakami129** [comment]
这个端口号，是你梯子的端口。

在容器中没有办法使用http://localhost:xxx

所以需要http://host.docker.interna  这个dns代理到宿主机

**Comment by MisterRain-web** [comment]
请问你解决了吗，我也出现这个问题

**Comment by tomridder** [comment]
需要在 baseurl 后面加上 /v1

**Comment by MisterRain-web** [comment]
谢谢您大佬，我发现我问错问题了。我的问题也是“有人物出现，配置了 key和 baseurl，但是一直不回复，是不是http-proxy导致的”。然后我的http-proxy配置的也是梯子的端口号：http://host.docker.interna:33210&nbsp; 但还是不能对话，是什么问题呢。谢谢您!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yakami129/VirtualWife"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月19日(星期五) 晚上9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yakami129/VirtualWife] linux部署，问问题有问题 (Issue #69)





 
需要在 baseurl 后面加上 /v1

**Comment by sunreview** [comment]
需要在 baseurl 后面加上 /v1，已经解决
