### ISSUE TITLE
load default character ERROR: no such table: apps_customrolemodel

### ISSUE THREAD

**Issue by maidenfortress2020** [yakami129/VirtualWife#7]
Hi yakami,
when I execute the cmd: python manage.py makemigrations,
it reports errors like this: no such table: apps_customrolemodel
How can I create these tables used in the python?thx.

**Comment by yakami129** [comment]
1. delete file domain-chatbot/apps/migrations
2. delete file domain-chatbot/db/db.sqlite3
3. run python manage.py makemigrations 
4. run python manage.py migrate
